[package]
name = "qyron-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# notcurses = "3.2.2"

[dependencies.pyo3]
version = "0.18.1"
features = ["auto-initialize"]
